mj:
  discord:
    guild-id:
    channel-id:
    user-token:
    session-id:
    user-agent:
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: baidu
  queue:
    timeout-minutes: 8
    core-size: 3
    queue-size: 10
  baiduTranslate:
    appid:
    appSecret:

aliyun:
  accessKeyId:
  accessKeySecret:
  oss:
    endpoint:
    bucket-name: